version: '2'
services:
  flask:
    restart: always
    build: .
    ports:
      - "5000:5000"
    env_file: docker.env
    depends_on:
      - migrate
    volumes:
      - .:/app
    command: python /app/manage.py runserver

  migrate:
    build: .
    depends_on:
      - postgis
      - redshift
      - redis
    env_file: docker.env
    volumes:
      - .:/app
    command: python /app/manage.py init

  postgis:
    build: ./deploy/postgis

  redshift:
    build: ./deploy/redshift

  redis:
    image: redis:latest

