app:
  restart: always
  build: ./app
  expose:
    - 5000
  links:
    - postgis:postgis
    - redshift:redshift
    - redis:redis
  env_file: docker.env
  volumes:
    - ./app:/app
  command: python /app/manage.py runserver

nginx:
  restart: always
  build: ./nginx
  ports:
    - 5000:80
  volumes_from:
    - app
  links:
    - app:app

postgis:
  restart: always
  build: ./postgis
  volumes_from:
    - data_pg
  expose:
    - 5432

redshift:
  restart: always
  build: ./redshift
  volumes_from:
    - data_rs
  expose:
    - 5432

redis:
  restart: always
  image: redis:latest
  expose:
    - 6379

data_pg:
  restart: always
  image: alpine
  volumes:
    - /var/lib/postgresql
  command: "true"

data_rs:
  restart: always
  image: alpine
  volumes:
    - /var/lib/postgresql
  command: "true"
