#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

# Source function library.
. /etc/init.d/functions

start() {
    # code to start app comes here 
    # example: daemon program_name &
    # ...do nothing...
    echo "Humane Worker Euthanizer is loaded."
}

stop() {
	# code to stop app comes here 
	# example: killproc program_name
	echo "Humane Worker Euthanizer: Euthanizing worker processes..."
	touch /var/tmp/terminate_runloop
	while [ $(pgrep -f runloop.py | wc -l) -gt "0" ]; do
		sleep 1;
	done;
	echo "Processes have exited."

}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
