#!/bin/bash
# processname: workersunion
# chkconfig: 2345 20 80
# description: Securing the right for workers to finish the job.

# Source function library.
. /etc/init.d/functions

start() {
    # code to start app comes here 
    # example: daemon program_name &
    # ...do nothing...
    touch /var/lock/subsys/workersunion;
    echo "Workers Union: Workers have Unionized.";
}

stop() {
	# code to stop app comes here 
	# example: killproc program_name
	echo "Workers Union: Securing the right for workers to finish the job...";
	while [ $(pgrep -f worker.py | wc -l) -gt "0" ]; do
		echo "Workers Union: $(date) - Waiting on $(pgrep -f worker.py | wc -l) workers...";
		sleep 1;
	done;
	
	tail /opt/python/log/worker.log
	echo "Workers Union: All workers have finished and left.";
	
	rm -f /var/lock/subsys/unionboss;
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       chkconfig --list unionboss
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
